### ISSUE TITLE
Question; dependantJob vs dependencies

### ISSUE THREAD

**Issue by connors511** [ksassnowski/venture#12]
I was playing around with the `WorkflowJob` and noticed that `dependantJobs` is an array of instances, while `dependencies` is just an array of class names.

Is there a particular reason why `DependencyGraph->getDependantJobs($job)` and `DependencyGraph->getDependencies($job)` don't both resolve to instances of jobs?

For reference;
```php
    public function getDependantJobs($job): array
    {
        $key = is_object($job) ? get_class($job) : $job;

        return collect($this->graph[$key]['out_edges'])
            ->map(function (string $dependantJob) {
                return $this->graph[$dependantJob]['instance'];
            })
            ->toArray();
    }

    public function getDependencies($job): array
    {
        $key = is_object($job) ? get_class($job) : $job;

        return $this->graph[$key]['in_edges'];
    }
```

**Comment by ksassnowski** [comment]
The main reason is that the only reason we need to look up the dependencies of a job is to check if all of its dependencies have finished. So we don't actually need an instance for them, since we're using the class name to look them up.

It's a different story for the dependent Jobs, however, since they might have to be immediately dispatched. In this case we need the job instance.
