### ISSUE TITLE
Running normal jobs fails

### ISSUE THREAD

**Issue by viezel** [ksassnowski/venture#19]
When running a regular job then your event listener fails, due to the ´command` is not part of the job payload, as data can be an empty string. 

```php
Queue::push(\App\Jobs\TestJob::class)
```

```php
private function getJobInstance(Job $job)
{
    return unserialize($job->payload()['data']['command']);
}
```

```
[2021-01-13 15:22:13] local.ERROR: Cannot access offset of type string on string {"exception":"[object] (TypeError(code: 0): Cannot access offset of type string on string at /var/www/html/vendor/sassnowski/venture/src/WorkflowEventSubscriber.php:79)
[stacktrace]
#0 /var/www/html/vendor/sassnowski/venture/src/WorkflowEventSubscriber.php(50): Sassnowski\\Venture\\WorkflowEventSubscriber->getJobInstance()
```

**Comment by ksassnowski** [comment]
Can you show me what `TestJob` looks like? I'm not quite sure what you mean by a "normal" job.

**Comment by viezel** [comment]
A vanilla laravel job that does not implement WorkflowStep.

```php
class TestJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function handle()
    {
        info("Hello World");
    }
}
```

**Comment by ksassnowski** [comment]
The problem is that you're pushing the string containing the job name to the queue, not an instance of the job itself. So

```php
// This works…
Queue::push(new TestJob());

// This doesn't
Queue::push(TestJob::class);
```

What tipped me off was that the stacktrace pointed to the `handleJobFailed` handler in the `WorkflowEventSubscriber`. Laravel actually complains about the same thing internally.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/5139098/104482702-87cacd80-55c7-11eb-927d-65d6cf38f759.png">

This should probably not cause an exception coming from Venture, but dispatching jobs regularly works as intended.

**Comment by viezel** [comment]
Doh! 🙄 my bad
