### ISSUE TITLE
Ability to add closure as a job

### ISSUE THREAD

**Issue by morrislaptop** [ksassnowski/venture#24]
Would this be possible?

```php
return Workflow::define('Build Job')
            ->addJob(function () use ($podcast) {
                 $podcast->publish();
            });
```

**Comment by ksassnowski** [comment]
Currently it wouldn't work because of how Venture keeps track of references. But it's definitely something that should be possible in the future. I'm still having a look at #14 which proposes changes to how Venture keeps track of dependencies between jobs. I think that would make adding a closure to a workflow possible as well.

I don't know when I will be able to get to it, however, since I'm in the middle of moving right now.

**Comment by ksassnowski** [comment]
This is now possible in v4. Here's the relevant section in the docs: https://laravel-venture.com/usage/configuring-workflows.html#adding-closures-as-jobs
