### ISSUE TITLE
Type of workflow

### ISSUE THREAD

**Issue by homeoftheunits** [ksassnowski/venture#4]
Hey,

which type of class should an workflow be? Is it an Laraval Job or an standalone class?

Cheers
Ralf

**Comment by ksassnowski** [comment]
Hi there,

maybe the docs could be clearer on this. There are two components to a workflow, the workflow _definition_ and the _jobs_ that make up the workflow.

The **definition** is a standalone class that extends from `Sassnowski\Venture\AbstractWorkflow`. This class is where you define the jobs that make up the workflow as well as the dependencies between them. See [this section in the docs](https://laravel-venture.netlify.app/usage/configuring-workflows.html#creating-a-workflow-definition) for more information.

The **jobs** are regular Laravel jobs. The only thing you need to change about them is to include the `WorkflowStep` trait that comes with Venture. [Here's the relevant section in the docs](https://laravel-venture.netlify.app/usage/preparing-your-jobs.html#overview).

Let me know if this cleared up your confusion 🤘

**Comment by homeoftheunits** [comment]
ok, thank you :) 

Than maybe it makes sense, that you hint the $job Parameters in the Model class, maybe like:
```
private function markJobAsFinished(ShouldQueue $job): void
```

**Comment by ksassnowski** [comment]
I don't think that would work for two reasons:

1. Jobs inside a workflow don't _have_ to be async, although they probably are in 99% of the cases. As such it's not guaranteed that a job will implement the `ShouldQueue` interface.
2. `ShouldQueue` is an empty interface. I don't think it makes sense semantically to typehint a parameter with it an empty interface since you wouldn't be able to do anything with.

If PHP allowed typehinting traits we could annotate it as a `WorkflowStep`, but alas we can't :)
