### ISSUE TITLE
Nesting workflows

### ISSUE THREAD

**Issue by connors511** [ksassnowski/venture#6]
Venture looks super interesting and very suitable for an upcoming project of mine.
Could be super sweet if you could nest workflows to increase reusability of common workflows.

For instance, the following example;

```php

class EncodeWorkflow extends AbstractWorkflow
{
    public function definition(): WorkflowDefinition
    {
        return Workflow::define('Encode Podcast')
            ->addJob(new EncodePodcast($this->podcast, 'mp3'))
            ->addJob(new EncodePodcast($this->podcast, 'wav'));
    }
}

class OptimizeWorkflow extends AbstractWorkflow
{
    public function definition(): WorkflowDefinition
    {
        return Workflow::define('Optimize Podcast')
            ->addJob(new AnalyzePodcast($this->podcast))
            ->addJob(new OptimizePodcast($this->podcast), [AnalyzePodcast::class])
            ->addWorkflow((new EncodeWorkflow($this->podcast))->definition(), [OptimizePodcast::class]);
    }
}

class PublishWorkflow extends AbstractWorkflow
{
    public function definition(): WorkflowDefinition
    {
        return $publishWorkflow = Workflow::define('Publish Podcast')
            ->addJob(new ReleaseOnTransistorFM($this->podcast))
            ->addJob(new ReleaseOnApplePodcasts($this->podcast));
    }
}


$processWorkflow = Workflow::define('Release Podcast')
    ->addJob(new ProcessPodcast($this->podcast))
    ->addWorkflow((new OptimizeWorkflow($this->podcast))->definition(), [ProcessPodcast::class])
    ->addWorkflow((new PublishWorkflow($this->podcast))->definition(), [OptimizeWorkflow::class]);

```

Have you considered something like this for the package?
If so, do you already have an idea for such an implementation, or would you be open to a PR when I start on the project that would benefit from such a feature?

**Comment by ksassnowski** [comment]
This sounds like a really interesting idea!

I think the best way to implement this would be to "unpack" the workflow that is being added and add each of its jobs to the receiving workflow. This way, we don't have to worry about any special case handling after we've added the workflow. Off the top of my head, these are the challenges that would need to be solved:

- Since a workflow can have multiple "root" nodes, i.e. jobs without dependencies, we would have to ensure that their dependency gets set correctly. So when calling `addWorkflow($workflow, [SomeJob::class])` we would have to add `SomeJob` as the dependency for all jobs without dependencies in `$workflow`.
- Because of how Venture currently keeps track of dependencies (via the class name string), there is a limitation where you cannot add multiple instances of the same job to a workflow. So your `EncodeWorkflow` actually wouldn't work the way you expect it to, since the second instance of `EncodePodcast` would essentially override the first one. When unpacking a workflow, we need to ensure that no duplicate jobs get added. This is a limitation that I would really like to get rid off at some point, but I haven't yet figured out a way to do so.

I'm definitely open for a PR, but I would like to discuss the approach first so we don't do a bunch of work that doesn't lead anywhere 👍

**Comment by connors511** [comment]
We've just started the specifications on the project today, so there's still a fair bit of time before we get to implementation leaving plenty of time for discussing a nested workflow feature 👌

The example was just a quick proof of concept and I realized the limitation of job names you mention. Workaround-able if you just extend base encoder with specific jobs for each type :D

I've just spent a few minutes skimming the code, so I haven't had time to dig deeper yet. My initial thought was though, to kinda treat the nested workflows as separate jobs. So the parent workflow just sees them as a single job without any knowledge of what they might contain. 
Calling `addWorkflow` could internally 'just' wrap it in a `NestedWorkflowJob` which when handled would run the workflow mechanism as if you've started the nested flow yourself.
This would however introduce some limitations around the dependecies and root jobs of nested flows as you mention. I'm not sure if it's an issue though. 
At least I can't really think of a case where you can't think of the entire flow as a separate job and either wait to start the entire flow based on the dependencies or start the flow as a root job without any dependcies.

**Comment by ksassnowski** [comment]
I think this is also a valid approach. However, there are a couple of design/architectural reasons why I would probably not want to implement it like this.

- I'm currently working on a Venture Dashboard package that visualizes the dependency graph of a workflow. In this graph, I definitely want each individual job in the workflow to show up, regardless of how it got added. By adding a kind of proxy job that wraps an entire workflow this would get significantly harder to achieve.
- If we were to "unroll" the added workflow, we could use the existing testing helpers to test this feature. Because you would just have to assert that a workflow has the correct jobs with the correct dependencies. Which leads me to..
- I want to avoid introducing special cases if possible. And I think that adding a workflow to another workflow is semantically identical to adding each of the workflow's jobs individually.

So the property I would like this feature to have is

```
$workflowA->addWorkflow($workflowB)

is isomorphic to

for job : $workflowB
    add job to $workflowA

```

_(which would actually be a nice test case, now that I think about it)_

---

I actually thought of another challenge: adding a dependency to a workflow. This should definitely be possible, but could be a bit trickier to achieve. I think that depending on a workflow basically means depending on the leaf nodes of the workflow.

Assuming the following definitions

```php
class WorkflowA extends AbstractWorkflow
{
    public function definition(): WorkflowDefinition
    {
        $definition
            ->addJob(Job1::class)
            ->addJob(Job2::class, [Job1::class]) // Leaf node
            ->addJob(Job3::class); // Leaf node
    }
}

class WorkflowB extends AbstractWorkflow
{
    public function definition(): WorkflowDefinition
    {
        return Workflow::define('Workflow B')
            ->addJob(new Job4())
            ->addWorkflow(new WorkflowA())
            ->addJob(new Job5(), [WorkflowA::class]);
    }
}
```

`->addJob(new Job5(), [WorkflowA::class])` would have to expand to `addJob(new Job5(), [Job2::class, Job3::class])`.

**Comment by connors511** [comment]
I do see the benefit of just unrolling the workflow when nesting them (love the sound of a dashboard for visualisation!), and after prototyping a little, it also seems a lot easier and simpler than I anticipated.

Some quick dirty stuff to test out the dependency expansion for leaf nodes;
```php
class DependencyGraph {
    ...

    public function getLeaflets(): array
    {
        $leafs = [];
        $toProcess = $this->getJobsWithoutDependencies();

        while (!empty($toProcess)) {
            $job = array_pop($toProcess);
            $dependants = $this->getDependantJobs($job);

            if (empty($dependants)) {
                $leafs[] = $job;
            } else {
                $toProcess += $dependants;
            }
        }

        return $leafs;
    }
}
```

```php

it('returns a list of leaflets with single dependency', function () {
    $job1 = new TestJob1();
    $job2 = new TestJob2();
    $job3 = new TestJob3();

    $this->graph->addDependantJob($job1, []);
    $this->graph->addDependantJob($job2, [TestJob1::class]);
    $this->graph->addDependantJob($job3, []);

    assertEquals([$job3, $job2], $this->graph->getLeaflets());
});

it('returns a list of leaflets with multiple dependencies', function () {
    $job1 = new TestJob1();
    $job2 = new TestJob2();
    $job3 = new TestJob3();
    $job4 = new TestJob4();

    $this->graph->addDependantJob($job1, []);
    $this->graph->addDependantJob($job2, [TestJob1::class]);
    $this->graph->addDependantJob($job3, [TestJob1::class]);
    $this->graph->addDependantJob($job4, [TestJob2::class]);

    assertEquals([$job3, $job4], $this->graph->getLeaflets());
});
```

**Comment by ksassnowski** [comment]
So I actually have a version that is 85% done already. You can have a look at the draft PR that I opened (#7). The most important change was how the `DependencyGraph` class internally represents the graph. Previously I was keeping track of all things in different arrays (`dependencies`, `dependants`, `instances`). This was a lot of extra work, that wasn't really necessary. Now, I'm using a proper adjacency list to represent the graph. This makes manipulating it so much easier.

I'm fairly confident that I will be able to finalize this feature this week.

**Comment by connors511** [comment]
Looks great so far 👍

**Comment by ksassnowski** [comment]
I have finished implementing this feature. It will be part of the `2.0.0` release of Venture since there are a few breaking changes. I expect version to be released some time next week as I still have to update the documentation. You can check out the `2.x` branch if you want to take it for a test run.

**Comment by connors511** [comment]
Cool, will do. Thanks for the quick & awesome work :)

**Comment by connors511** [comment]
Fixed by https://github.com/ksassnowski/venture/pull/7
